-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 15:15:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sikatup_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sikatup_db` ;

-- -----------------------------------------------------
-- Schema sikatup_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sikatup_db` DEFAULT CHARACTER SET utf8 ;
USE `sikatup_db` ;

-- -----------------------------------------------------
-- Table `sikatup_db`.`SiKatupSession`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sikatup_db`.`SiKatupSession` ;

CREATE TABLE IF NOT EXISTS `sikatup_db`.`SiKatupSession` (
  `id` VARCHAR(40) NULL,
  `ip_address` VARCHAR(45) NULL,
  `timestamp` INT(11) NULL,
  `data` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sikatup_db`.`Jabatan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sikatup_db`.`Jabatan` ;

CREATE TABLE IF NOT EXISTS `sikatup_db`.`Jabatan` (
  `idJabatan` INT NOT NULL AUTO_INCREMENT,
  `nama_jabatan` VARCHAR(45) NULL,
  PRIMARY KEY (`idJabatan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sikatup_db`.`Pengurus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sikatup_db`.`Pengurus` ;

CREATE TABLE IF NOT EXISTS `sikatup_db`.`Pengurus` (
  `idPengurus` INT NOT NULL AUTO_INCREMENT,
  `nama_pengurus` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `alamat` VARCHAR(100) NULL,
  `foto` VARCHAR(100) NULL,
  `status` INT(1) NULL,
  `dibuat` TIMESTAMP NULL,
  `diedit` TIMESTAMP NULL,
  `Jabatan_idJabatan` INT NOT NULL,
  PRIMARY KEY (`idPengurus`, `Jabatan_idJabatan`),
  INDEX `fk_Pengurus_Jabatan_idx` (`Jabatan_idJabatan` ASC),
  CONSTRAINT `fk_Pengurus_Jabatan`
    FOREIGN KEY (`Jabatan_idJabatan`)
    REFERENCES `sikatup_db`.`Jabatan` (`idJabatan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sikatup_db`.`Kegiatan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sikatup_db`.`Kegiatan` ;

CREATE TABLE IF NOT EXISTS `sikatup_db`.`Kegiatan` (
  `idKegiatan` INT NOT NULL AUTO_INCREMENT,
  `judul_kegiatan` VARCHAR(100) NULL,
  `thumbnail` VARCHAR(100) NULL,
  `slug` TEXT NULL,
  `konten` TEXT NULL,
  `create` TIMESTAMP NULL,
  `update` TIMESTAMP NULL,
  `kegiatan_status` INT(1) NULL,
  `Pengurus_idPengurus` INT NOT NULL,
  PRIMARY KEY (`idKegiatan`, `Pengurus_idPengurus`),
  INDEX `fk_Kegiatan_Pengurus1_idx` (`Pengurus_idPengurus` ASC),
  CONSTRAINT `fk_Kegiatan_Pengurus1`
    FOREIGN KEY (`Pengurus_idPengurus`)
    REFERENCES `sikatup_db`.`Pengurus` (`idPengurus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sikatup_db`.`Produk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sikatup_db`.`Produk` ;

CREATE TABLE IF NOT EXISTS `sikatup_db`.`Produk` (
  `idProduk` INT NOT NULL AUTO_INCREMENT,
  `nama_produk` VARCHAR(45) NULL,
  `foto_produk` VARCHAR(100) NULL,
  `deskripsi_produk` VARCHAR(100) NULL,
  `slug_produk` TEXT NULL,
  `cp_produk` VARCHAR(45) NULL,
  `Pengurus_idPengurus` INT NOT NULL,
  PRIMARY KEY (`idProduk`, `Pengurus_idPengurus`),
  INDEX `fk_Produk_Pengurus1_idx` (`Pengurus_idPengurus` ASC),
  CONSTRAINT `fk_Produk_Pengurus1`
    FOREIGN KEY (`Pengurus_idPengurus`)
    REFERENCES `sikatup_db`.`Pengurus` (`idPengurus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
